name: Tests

on:
    push:
        branches:
            - master
            - v9.0
            - v8.0
        paths-ignore:
            - '**.md'
    pull_request:
        branches:
            - master
            - v9.0
            - v8.0
        paths-ignore:
            - '**.md'
    # Allow manually triggering the workflow
    workflow_dispatch:

jobs:
    test:
        runs-on: "ubuntu-latest"

        strategy:
            matrix:
                php-version:
                    - "8.2"
                    - "8.3"
                    - "8.4"

        name: PHP ${{ matrix.php-version }} tests

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: ldap
                    coverage: none

            -   name: "Install Composer"
                uses: "ramsey/composer-install@v3"

            -   name: "Run PHPUnit"
                run: ./vendor/bin/phpunit --configuration phpunit.xml --colors
